# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Django Bower
tagline:          Using Bower with Django

baseurl:          /

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/PabloVallejo/django-bower
